/*
 * SysCtl_cfg.h
 *
 *  Created on: Apr 6, 2020
 *      Author: Youssef Harby
 */


#ifndef SYSCTL_CFG_H_
#define SYSCTL_CFG_H_

/********************************************************************************
 * 								  Included Files								*
 ********************************************************************************/

#include "tm4c123gh6pm_registers.h"


/********************************************************************************
 * 								Preprocessor Macros								*
 ********************************************************************************/

/* Definition of the pre-decided frequency */
#define SYSCTL_REQUIRED_FREQUENCY		SYSCTL_FREQ_80

/* Definitions of some of the available frequencies */
#define SYSCTL_FREQ_8			0
#define SYSCTL_FREQ_12_5		1
#define SYSCTL_FREQ_16			2
#define SYSCTL_FREQ_25			3
#define SYSCTL_FREQ_33_33		4
#define SYSCTL_FREQ_40			5
#define SYSCTL_FREQ_50			6
#define SYSCTL_FREQ_66_67		7
#define SYSCTL_FREQ_80			9

/* Definitions of modules clock registers mask */
#define SYSCTL_CLOCK_ENABLED			1
#define SYSCTL_CLOCK_DISABLED			0

/* Watchdog Timer Modules */
#define SYSCTL_WATCHDOG_MODULE_0_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_WATCHDOG_MODULE_1_STATUS			SYSCTL_CLOCK_DISABLED

/* Timer Modules */
#define SYSCTL_TIMER_MODULE_0_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_TIMER_MODULE_1_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_TIMER_MODULE_2_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_TIMER_MODULE_3_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_TIMER_MODULE_4_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_TIMER_MODULE_5_STATUS			SYSCTL_CLOCK_DISABLED

/* Wider Timer Modules */
#define SYSCTL_WTIMER_MODULE_0_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_WTIMER_MODULE_1_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_WTIMER_MODULE_2_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_WTIMER_MODULE_3_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_WTIMER_MODULE_4_STATUS			SYSCTL_CLOCK_DISABLED
#define SYSCTL_WTIMER_MODULE_5_STATUS			SYSCTL_CLOCK_DISABLED

/* GPIO Modules */
#define SYSCTL_GPIO_MODULE_0_STATUS				SYSCTL_CLOCK_ENABLED
#define SYSCTL_GPIO_MODULE_1_STATUS				SYSCTL_CLOCK_ENABLED
#define SYSCTL_GPIO_MODULE_2_STATUS				SYSCTL_CLOCK_ENABLED
#define SYSCTL_GPIO_MODULE_3_STATUS				SYSCTL_CLOCK_ENABLED
#define SYSCTL_GPIO_MODULE_4_STATUS				SYSCTL_CLOCK_ENABLED
#define SYSCTL_GPIO_MODULE_5_STATUS				SYSCTL_CLOCK_ENABLED

/* Micro Direct Memory Address (UDMA) */
#define SYSCTL_UDMA_MODULE_STATUS				SYSCTL_CLOCK_DISABLED

/* Hibernation Module */
#define SYSCTL_HIBERNATION_MODULE_STATUS		SYSCTL_CLOCK_ENABLED

/* UART Modules */
#define SYSCTL_UART_MODULE_0_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_UART_MODULE_1_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_UART_MODULE_2_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_UART_MODULE_3_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_UART_MODULE_4_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_UART_MODULE_5_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_UART_MODULE_6_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_UART_MODULE_7_STATUS				SYSCTL_CLOCK_DISABLED

/* SSI (SPI) Modules */
#define SYSCTL_SSI_MODULE_0_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_SSI_MODULE_1_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_SSI_MODULE_2_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_SSI_MODULE_3_STATUS				SYSCTL_CLOCK_DISABLED

/* I2C Modules */
#define SYSCTL_I2C_MODULE_0_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_I2C_MODULE_1_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_I2C_MODULE_2_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_I2C_MODULE_3_STATUS				SYSCTL_CLOCK_DISABLED

/* USB Module */
#define SYSCTL_USB_MODULE_STATUS				SYSCTL_CLOCK_DISABLED

/* CAN Module */
#define SYSCTL_CAN_MODULE_0_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_CAN_MODULE_1_STATUS				SYSCTL_CLOCK_DISABLED

/* ADC Modules */
#define SYSCTL_ADC_MODULE_0_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_ADC_MODULE_1_STATUS				SYSCTL_CLOCK_DISABLED

/* Analog Comparator Module */
#define SYSCTL_ACMP_MODULE_STATUS				SYSCTL_CLOCK_DISABLED

/* PWM Modules */
#define SYSCTL_PWM_MODULE_0_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_PWM_MODULE_1_STATUS				SYSCTL_CLOCK_DISABLED

/* Quadrature Encoder Interface Modules */
#define SYSCTL_QEI_MODULE_0_STATUS				SYSCTL_CLOCK_DISABLED
#define SYSCTL_QEI_MODULE_1_STATUS				SYSCTL_CLOCK_DISABLED

/* EEPROM Module */
#define SYSCTL_EEPROM_MODULE_STATUS				SYSCTL_CLOCK_DISABLED


#endif /* SYSCTL_CFG_H_ */
